name: Type Checking
on: [push]
jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🏗️ python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: ⬇️ Python Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
      - name: ⬇️ Python Dependencies
        run: poetry install --only main

      - name: 🏗️ node
        uses: actions/setup-node@v2
        with:
          node-verion: 18
      - name: ⬇️ all packages
        run: npm install
      - name: 🏃 pyright
        run: poetry run npx pyright
